name    'Jimdo-check_logfile'
version '0.0.1'
source 'git://github.com/Jimdo/puppet-check_logfile'
author 'LarsFronius,Ole Michaelis'
dependency 'ripienaar/concat', '0.2.0'
dependency 'puppetlabs/stdlib', '3.0.0'
license 'UNKNOWN'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'
